### ISSUE TITLE
Mac binary not working

### ISSUE THREAD

**Issue by matt6412** [ZclassicCommunity/electrum-zclassic#18]
Using mac os Mojave 10.14.6 with latest binary just released v3.2.4 

Had previous version installed, installed this over that, opened, decrypted wallet, got into electrum and server list indicated chain split and blocks were not downloading, with no red or green sign on bottom right of electrum status.  Exited, restarted, now fails to open.

**Comment by hTrap** [comment]
Hey, this is the issue of currupted headers in your local copy of
blockchain headers.
Kindly backup your wallet carefully and remove ~/.electrum-zclassic dir.

**Comment by matt6412** [comment]
Fixed! thank you sir!
