### ISSUE TITLE
Request for easier installation methods

### ISSUE THREAD

**Issue by Freeter-Prince** [ZclassicCommunity/electrum-zclassic#3]
Hi,
I guess it's due to my lack of skills in programming, I failed to install the wallet in accordance with the guidance, after trying many times on my mac, so I am wondering if there's an easier way of installation, such as providing a .DMG or .exe installation package from which more people like me can install the wallet. Please kindly advise if it is possible. Thanks in advance.

**Comment by mexican1973** [comment]
HI Freeter-Prince. 
Yes it is possible. We should be providing in some days some binaries to be able to install it in an easy way. We just need to ask @thedevworks --> James to provide this. Maybe you can ask him in the teledram group ?
https://t.me/ZClassicCoin
https://t.me/ZclassicCE
Thanks
Best regrads
Heinrich

**Comment by Freeter-Prince** [comment]
> HI Freeter-Prince.
> Yes it is possible. We should be providing in some days some binaries to be able to install it in an easy way. We just need to ask @thedevworks --> James to provide this. Maybe you can ask him in the teledram group ?
> https://t.me/ZClassicCoin
> https://t.me/ZclassicCE
> Thanks
> Best regrads
> Heinrich

Thank you Heinrich for your reply，I will try asking James about it.
