### ISSUE TITLE
electrum-zclassic v3.2.6

### ISSUE THREAD

**Issue by ttl99** [ZclassicCommunity/electrum-zclassic#31]
what happens to the zclassic wallet? I sent funds to my wallet but it does not finish connecting the server electrum.800crypto.club *, my funds were stuck

**Comment by Cosmatinco** [comment]
I have the same problem i have sent the found from miningpool hub to the wallet v3.25 and the founds doesnt show up .. also i have no connection and using the same server electrum.800crypto.club.?? any advices

**Comment by ttl99** [comment]
It seems to be a problem of the server, I do not update after block 801789, it remains to wait, if you update the wallet or open a new server, hopefully someone else comments if you have any solution, I advise you to keep your wallet open to see if we can get more together. nodes

**Comment by Cosmatinco** [comment]
hi bro .. i have updated the wallet so now i have v3.26 and the same number of nodes 801789 like you .. my wallet is online but the coins still doesnt show up ... i will ask as well the mininghub pool hub what have happened with the manual id payment .. if they can see if the transaction was done ... cheers for corresponding for the issue .. hope we solve it soon ..

**Comment by cryptoprofutonium** [comment]
It was a compaction issue on the server, should be fixed now.

**Comment by ttl99** [comment]
I admire the prompt response they gave to the error and this encourages me to continue believing in the project and becoming a fan, very well

**Comment by Cosmatinco** [comment]
... yesss it look like this casue my founds has arrived in to the wallet but its sinhronizing again the wallet .. more nodes .. look like all will works again .. cheers

**Comment by Cosmatinco** [comment]
... hi guys i am back ... looks like the same problems goes on .. my wallet after it was updated to the latest version all the founds has arrived like i said but since then the wallet is still synchronizing and it doesnt show any more the number of the ZCL in it .. looks like there is another problem with the server .. ? does your wallet work good guys ???

**Comment by ttl99** [comment]
What is the problem exactly, because I do not understand, you mean that your balance does not appear in your wallet

**Comment by Cosmatinco** [comment]
Hi bro,
yes it doesnt appeared. The wallet is synchronizing  all of the time and the founds are not visible... its saying synchronizing..
cheers

**Comment by ttl99** [comment]
If you updated your wallet to version 3.2.6 and had a previous version, I think in the new wallet you should use your recovery phrase or seed, the server is working fine, I have not had any problems so far

**Comment by Cosmatinco** [comment]
Hi... thank you for helping but looks like the seeds are already the same even if i had updated to the last version ... i have 2427017 blocks downloaded ... but is still synchronizing...

**Comment by ttl99** [comment]
are you sure? Are we still talking about zclassic? because the current block is 841284 and you mention 2427017, check that your wallet's server is correct, adjust your server in the automatic server box

**Comment by Cosmatinco** [comment]
Yes i am sure i have electrum zclassic v3.2.6 wallet and the last node number is 2427017 blocks ..connected node high ... saying and the server is electrum.800crypto.club port: 50002 ... i should have green light on the right bottom side of the wallet which means thats working fine .. i cant upload the screen shot on github i dont know why .. cheers

**Comment by Cosmatinco** [comment]
![Screen Shot 2020-08-04 at 4 36 18 PM copy](https://user-images.githubusercontent.com/62122270/89408095-2f41fb00-d720-11ea-9c10-66f99f67dee2.png)

**Comment by Cosmatinco** [comment]
![Screen Shot 2020-08-04 at 4 36 27 PM](https://user-images.githubusercontent.com/62122270/89408160-484aac00-d720-11ea-9e26-1c96c5f1bce6.png)

**Comment by Cosmatinco** [comment]
![Screen Shot 2020-08-01 at 5 59 03 PM](https://user-images.githubusercontent.com/62122270/89408271-6adcc500-d720-11ea-8fc5-2d69b64f50e6.png)

**Comment by Cosmatinco** [comment]
i have sent the mined  ZCL coins as well after the 18.7.20 to the wallet and nothing ...the found still not visible ... ??

**Comment by ttl99** [comment]
the design is somewhat different, I admit that the error you have is somewhat complicated is beyond my knowledge, the best thing I can think of is that first you save your wallet seed well step 2 uninstall the z classis wallet completely, check compatibility with your computer of the program that is for windows if you use windows or check if the program is for mac, I will try to upload some photos to try to help you

**Comment by ttl99** [comment]
![image](https://user-images.githubusercontent.com/68389566/89473512-a4292b00-d748-11ea-8c6e-7a4c42e1d8b1.png)

**Comment by ttl99** [comment]
![image](https://user-images.githubusercontent.com/68389566/89473585-da66aa80-d748-11ea-829c-b31effe4c1c1.png)

**Comment by ttl99** [comment]
![image](https://user-images.githubusercontent.com/68389566/89473617-f66a4c00-d748-11ea-89b4-12b036d3a74a.png)

**Comment by ttl99** [comment]
![image](https://user-images.githubusercontent.com/68389566/89473639-06822b80-d749-11ea-8e11-224fa981e59e.png)

**Comment by ttl99** [comment]
I hope the photos and the recommendation will serve you,

**Comment by ttl99** [comment]
I forgot, I also recommend that you check if you have antivirus activated, maybe that may be causing the problem, greetings
